set_property USER_SLR_ASSIGNMENT SLR1 [get_cells -quiet [list {i_gem*}]]
set_property USER_SLR_ASSIGNMENT SLR1 [get_cells -quiet [list {i_x2o_framework*}]]
set_property USER_SLR_ASSIGNMENT SLR1 [get_cells -quiet [list {i_axi_ipbus_bridge*}]]
set_property USER_SLR_ASSIGNMENT SLR1 [get_cells -quiet [list {i_ttc_clks*}]]
#set_property USER_SLR_ASSIGNMENT SLR1 [get_cells -quiet [list {i_mgts*}]]
set_property USER_SLR_ASSIGNMENT SLR1 [get_cells -quiet [list {i_board_system*}]]