name: cmsme0_env_test
channels:
  - conda-forge
  - defaults
dependencies:
  - awkward
  - colorama
  - cryptography
  - lxml
  - matplotlib
  - numpy
  - pandas
  - paramiko
  - pip
  - python=3.11
  - seaborn
  - scipy
  - tqdm
  - uproot
  - xmltodict
