cocotb:
	TOPLEVEL_LANG=vhdl SIM=questa python test_data_formatter.py

pytest:
	TOPLEVEL_LANG=vhdl SIM=questa pytest

# clean:
# 	rm -rf sim_build

verbose:
	TOPLEVEL_LANG=vhdl SIM=questa pytest -v -o log_cli=True
