# Load RUCKUS library
source -quiet $::env(RUCKUS_DIR)/vivado_proc.tcl

# Pkg
loadSource -path "$::DIR_PATH/pkg/gem_pkg.vhd"
loadSource -path "$::DIR_PATH/pkg/axi_pkg.vhd"
loadSource -path "$::DIR_PATH/pkg/ipb_addr_decode.vhd"
loadSource -path "$::DIR_PATH/pkg/ipbus_pkg.vhd"
loadSource -path "$::DIR_PATH/pkg/ttc_pkg.vhd"
loadSource -path "$::DIR_PATH/pkg/sca_pkg.vhd"
loadSource -path "$::DIR_PATH/pkg/registers.vhd"
#loadSource -path "$::DIR_PATH/pkg/mgt_pkg.vhd"

# Top
loadSource -path "$::DIR_PATH/gem_amc.vhd"

# Utils
loadSource -path "$::DIR_PATH/utils/axi_ipbus_bridge.vhd"
loadSource -path "$::DIR_PATH/utils/counter.vhd"
loadSource -path "$::DIR_PATH/utils/crc16.vhd"
loadSource -path "$::DIR_PATH/utils/crc16_ccitt.vhd"
loadSource -path "$::DIR_PATH/utils/crc_vfat3_daq.v"
loadSource -path "$::DIR_PATH/utils/gt_rx_link_ila_wrapper.vhd"
loadSource -path "$::DIR_PATH/utils/gt_tx_link_ila_wrapper.vhd"
loadSource -path "$::DIR_PATH/utils/ipbus_slave.vhd"
loadSource -path "$::DIR_PATH/utils/latch.vhd"
loadSource -path "$::DIR_PATH/utils/oneshot.vhd"
loadSource -path "$::DIR_PATH/utils/oneshot_cross_domain__xpm.vhd"
loadSource -path "$::DIR_PATH/utils/prbs7_4b_checker.vhd"
loadSource -path "$::DIR_PATH/utils/prbs7_4b_generator.vhd"
loadSource -path "$::DIR_PATH/utils/prbs7_8b_checker.vhd"
loadSource -path "$::DIR_PATH/utils/prbs7_8b_generator.vhd"
loadSource -path "$::DIR_PATH/utils/pulse_extend.vhd"
loadSource -path "$::DIR_PATH/utils/rate_counter.vhd"
loadSource -path "$::DIR_PATH/utils/running_mean.vhd"
loadSource -path "$::DIR_PATH/utils/seconds_counter.vhd"
loadSource -path "$::DIR_PATH/utils/synchronizer__xpm.vhd"

# TTC
loadSource -path "$::DIR_PATH/ttc/ttc.vhd"
loadSource -path "$::DIR_PATH/ttc/ttc_clocks_ultrascale.vhd"
loadSource -path "$::DIR_PATH/ttc/ttc_cmd.vhd"
loadSource -path "$::DIR_PATH/ttc/ttc_decoder.vhd"
loadSource -path "$::DIR_PATH/ttc/ttc_generator.vhd"

# DAQ
loadSource -path "$::DIR_PATH/daq/daq.vhd"
loadSource -path "$::DIR_PATH/daq/track_input_processor.vhd"
loadSource -path "$::DIR_PATH/daq/vfat_input_buffer.vhd"
loadSource -path "$::DIR_PATH/daq/vfat_input_serializer.vhd"
loadSource -path "$::DIR_PATH/daq/data_concatenator.vhd"

# Trigger
loadSource -path "$::DIR_PATH/trigger/trigger.vhd"
loadSource -path "$::DIR_PATH/trigger/sbit_monitor.vhd"
loadSource -path "$::DIR_PATH/trigger/trigger_input_processor.vhd"
loadSource -path "$::DIR_PATH/trigger/trigger_output.vhd"
#loadSource -path "$::DIR_PATH/trigger/trigger_me0.vhd"

# Tests
loadSource -path "$::DIR_PATH/tests/gem_tests.vhd"
loadSource -path "$::DIR_PATH/tests/gbt_loopback_test.vhd"
loadSource -path "$::DIR_PATH/tests/gbt_prbs_loopback_test.vhd"

# Slow Control
loadSource -path "$::DIR_PATH/slow_control/slow_control.vhd"
loadSource -path "$::DIR_PATH/slow_control/gbtx_ic_controller.vhd"
loadSource -path "$::DIR_PATH/slow_control/sca_controller.vhd"
loadSource -path "$::DIR_PATH/slow_control/sca_rx.vhd"
loadSource -path "$::DIR_PATH/slow_control/sca_tx.vhd"

# OH
loadSource -path "$::DIR_PATH/oh/optohybrid.vhd"
loadSource -path "$::DIR_PATH/oh/oh_link_regs.vhd"
loadSource -path "$::DIR_PATH/oh/vfat3/vfat3_daq_monitor.vhd"
loadSource -path "$::DIR_PATH/oh/vfat3/vfat3_rx_aligner.vhd"
loadSource -path "$::DIR_PATH/oh/vfat3/vfat3_rx_link.vhd"
loadSource -path "$::DIR_PATH/oh/vfat3/vfat3_sc_rx.vhd"
loadSource -path "$::DIR_PATH/oh/vfat3/vfat3_sc_tx.vhd"
loadSource -path "$::DIR_PATH/oh/vfat3/vfat3_slow_control.vhd"
loadSource -path "$::DIR_PATH/oh/vfat3/vfat3_tx_link.vhd"
loadSource -path "$::DIR_PATH/oh/vfat3/vfat3_tx_stream.vhd"
loadSource -path "$::DIR_PATH/oh/link/6b8b.vhd"
loadSource -path "$::DIR_PATH/oh/link/8b6b.vhd"
loadSource -path "$::DIR_PATH/oh/link/6b8b_pkg.vhd"
loadSource -path "$::DIR_PATH/oh/link/link_oh_fpga.vhd"
loadSource -path "$::DIR_PATH/oh/link/link_oh_fpga_rx.vhd"
loadSource -path "$::DIR_PATH/oh/link/link_oh_fpga_tx.vhd"
loadSource -path "$::DIR_PATH/oh/link/link_rx_trigger.vhd"

# Misc
loadSource -path "$::DIR_PATH/misc/config_blaster.vhd"
loadSource -path "$::DIR_PATH/misc/gbt_link_mux_ge11.vhd"
loadSource -path "$::DIR_PATH/misc/gbt_link_mux_ge21.vhd"
loadSource -path "$::DIR_PATH/misc/gbt_link_mux_me0.vhd"
loadSource -path "$::DIR_PATH/misc/gem_system_regs.vhd"
loadSource -path "$::DIR_PATH/misc/oh_fpga_loader.vhd"
#loadSource -path "$::DIR_PATH/misc/gem_loader_bram.vhd"

# GBTX
loadSource -path "$::DIR_PATH/gbt_bank/gbt.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_bank_package.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_rx/gbt_rx_status.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_phasemon.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/mgt/mgt_latopt_bitslipctrl.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/xlx_k7v7/xlx_k7v7_gbt_bank_package.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/xlx_k7v7/xlx_k7v7_gbt_banks_user_setup.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/xlx_k7v7/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd"
loadSource -path "$::DIR_PATH/gbt_bank/core_sources/xlx_k7v7/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd"

# LpGBT
loadSource -path "$::DIR_PATH/lpgbt/lpgbt.vhd"
loadSource -path "$::DIR_PATH/lpgbt/lpgbtfpga_package.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/downlink_dataPath.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/downlink_fecEncoder.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/downlink_interleaver.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/uplink_dataPath.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/uplink_decoder.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/uplink_deinterleaver.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/uplink_deinterleaverFec12.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/uplink_deinterleaverFec5.vhd"
loadSource -path "$::DIR_PATH/lpgbt/dataPath/uplink_descrambler.vhd"
loadSource -path "$::DIR_PATH/lpgbt/fecCodec/fec_rsDecoderN15K13.vhd"
loadSource -path "$::DIR_PATH/lpgbt/fecCodec/fec_rsDecoderN31K29.vhd"
loadSource -path "$::DIR_PATH/lpgbt/fecCodec/fec_rsEncoderN7K5.vhd"
loadSource -path "$::DIR_PATH/lpgbt/gearbox/rxgearbox.vhd"
loadSource -path "$::DIR_PATH/lpgbt/gearbox/txgearbox.vhd"
loadSource -path "$::DIR_PATH/lpgbt/mgtFrameAligner/mgt_frameAligner.vhd"
loadSource -path "$::DIR_PATH/lpgbt/scrDscr/descrambler_51bitOrder49.vhd"
loadSource -path "$::DIR_PATH/lpgbt/scrDscr/descrambler_53bitOrder49.vhd"
loadSource -path "$::DIR_PATH/lpgbt/scrDscr/descrambler_58bitOrder58.vhd"
loadSource -path "$::DIR_PATH/lpgbt/scrDscr/descrambler_60bitOrder58.vhd"
loadSource -path "$::DIR_PATH/lpgbt/scrDscr/scrambler_36bitOrder36.vhd"

# LpGBT ASIC emul
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_10g_bidir.vhd"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_10g_tx.vhd"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/descrambler36bitOrder36.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/downLinkDeinterleaver.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/downLinkFECDecoder.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/downLinkRxDataPath.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_add_3.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_add_4.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_add_5.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_inv_3.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_log_3.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_multBy2_3.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_multBy2_4.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_multBy2_5.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_multBy3_4.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_multBy3_5.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gf_mult_3.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/gt_pkg.vhd"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/rs_decoder_N7K5.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/rs_encoder_N15K13.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/rs_encoder_N31K29.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/scrambler51bitOrder49.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/scrambler53bitOrder49.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/scrambler58bitOrder58.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/scrambler60bitOrder58.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/upLinkDataSelect.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/upLinkFECEncoder.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/upLinkInterleaver.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/upLinkScrambler.v"
loadSource -path "$::DIR_PATH/lpgbt/lpgbt_asic_emul/upLinkTxDataPath.v"

